---
apiVersion: v1
kind: Pod
metadata:
 name: jenkins-pod
 labels:
  author: Revathi
  ci: cd
spec:
 containers:
  - name: myjenkins
    image: jenkins
    ports:
     - containerPort: 8080
       hostPort: 8080
...

