---
apiVersion: v1
kind: ReplicationController
metadata:
 name: httpd-rc
 labels:
  type: webserver
spec:
 replicas: 3
 template:
  metadata: 
   name: httpdpod
   labels:
    type: webserver
  spec:
   containers:
    - name: myhttpd
      image: httpd
      ports:
       - containerPort: 8080
         hostPort: 8888
...

